### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by hadifarnoud** [daiyy2009/quick-preview#2]
I get `command 'extension.fullPreview' not found` error
using it on MacOS with latest VSCode

**Comment by JonShilale** [comment]
I get the same thing. 

Using latest VSCode on windows.

**Comment by redsparrowWang** [comment]
got this on latest VSCode

![screenshot 2018-11-30 10 38 41](https://user-images.githubusercontent.com/19768895/49263024-3d8c3e00-f48c-11e8-9089-d6ec7c5bd2d7.png)

**Comment by daiyy2009** [comment]
@hadifarnoud @JonShilale @redsparrowWang 

Thank you for all your comments.

It really doesn't work when i updated VSCode to the newest version(1.30.2).

But After tried the two steps below, it works:
- 1. disable & reload
![image](https://user-images.githubusercontent.com/13944527/50898749-0c1f6e80-144b-11e9-8a88-e56b2de1bcdf.png)
![image](https://user-images.githubusercontent.com/13944527/50898780-22c5c580-144b-11e9-8c4d-8462ab5f671e.png)
- 2. enable & reload

Then i opened a html file, press 'Ctrl + q, s', it works. Please try.

**Comment by redsparrowWang** [comment]
@daiyy2009 
hi, thanks for your contact, it's worked again, 
good job, thanks lot of. 🍻

**Comment by GratefulDave** [comment]
I am using vs code 1.30.2 on OSX 10.14.2 and am having the same issue. I tried the solution above and I still get command 'extension.SidePreview' not found when I try loading side preview and ctrl q + s is unrecognized.

**Comment by mymikemiller** [comment]
I'm getting the error too, and disabling/reenabling does not fix it :(

**Comment by redsparrowWang** [comment]
@mymikemiller
Hi. it's work in my version.(ctrl q + s, ctrl q + f is unrecognized.)
![ScreenShot_2019-04-03_10 48 45](https://user-images.githubusercontent.com/19768895/55447413-9b798f80-55fe-11e9-9c7f-a0fcd5b08064.png)

Try this, maybe it helps.
1. disable this plugin (or delete this plugin)
2. close VSCode
3. open VSCode
4. Enable this plugin (or reinstall this plugin)
5. close VSCode
6. open VSCode
7. confirm effect

other info:
![ScreenShot_2019-04-03_11 10 25](https://user-images.githubusercontent.com/19768895/55448148-95d17900-5601-11e9-87f8-3abcb02ab36a.png)

The extension 'daiyy.quick-html-previewer' uses the 'vscode.previewHtml' command which has been deprecated and will soon be removed. Create a problem that requires this extension to be updated to use VS Code's webview API.

https://github.com/daiyy2009/quick-preview/issues/4

**Comment by daiyy2009** [comment]
@redsparrowWang 
Done! Thank you. Plz update the extension.
