### ISSUE TITLE
Preview does not update/refresh correctly

### ISSUE THREAD

**Issue by vslmc** [daiyy2009/quick-preview#3]
"Good extension when working on a single file, 
but the extension fails to update to the current file when editing multiple documents (workspace update the current tab with a new file), 
and changing to a different line in the code causes the preview to show a different document previously opened."

**Comment by daiyy2009** [comment]
@Sekkei 

Thank you for your comment, but i can't reappear the issue you described.
Can you describe it in more detail or upload a gif?

**Comment by vslmc** [comment]
![previewbug](https://user-images.githubusercontent.com/28356741/51319118-84de8600-1a5c-11e9-9141-b4d153c54f93.gif)

**Comment by daiyy2009** [comment]
@Sekkei 
I'm sorry for the long wait.
I see you file suffix is xhtml, i will try to support it soon.

**Comment by daiyy2009** [comment]
@Sekkei 
Done! Please try the new published version of 0.5.0.

**Comment by vslmc** [comment]
I tested it and can confirm that it work perfekt!
Thank you very much

An option in the settings menu, to change the default font, would be nice
(oh I see: custom-style.css, this will work too)

**Comment by daiyy2009** [comment]
:)
