### ISSUE TITLE
Update VS Code WebView API

### ISSUE THREAD

**Issue by iamogbz** [daiyy2009/quick-preview#4]
### Description

`vscode.previewHtml` has been deprecated apparently.

<img width="469" alt="Screen Shot 2019-03-08 at 4 14 16 PM" src="https://user-images.githubusercontent.com/2528959/54056161-42fcd100-41bd-11e9-8917-f25a54e92e21.png">

**Comment by daiyy2009** [comment]
@iamogbz @redsparrowWang
done! Thank you.
