### ISSUE TITLE
Maintain URL fragment

### ISSUE THREAD

**Issue by Timmmm** [daiyy2009/quick-preview#6]
This is the only extension I have managed to find that actually *works* for side-by-side HTML preview (including javascript), so well done!

It would be nice if when it reloaded the file it could maintain the same URL fragment. This would mean I can use it to edit remarkjs presentations nicely. Currently every time I change the file it jumps back to the first slide.

**Comment by daiyy2009** [comment]
@Timmmm 
Do you mean we can lock the preview tab opened by certain url, even wen open another html file?

**Comment by Timmmm** [comment]
No I mean the fragment of the URL (the bit after the `#`) should be maintained when it is reloaded. However I looked at your code and the VSCode API and it doesn't seem like this is possible, since you just send it a chunk of HTML. Oh well.
